rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_meas.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_misc.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_module.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_scan.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sdio.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sdio.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_shim.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_cmd.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_cmdresp.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_event.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_ioctl.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_rx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_tx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_txrx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_cmdevent.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_ioctl.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_txrx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_util.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_wmm.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_wmm.h 
rm -f drivers/marvell/sd8897/wlan_src/gpl-2.0.txt 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11ac.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11ac.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11d.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11h.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11h.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_aggr.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_aggr.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_rxreorder.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_rxreorder.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_cfp.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_cmdevt.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_decl.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_fw.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_ieee.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_init.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_init.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_ioctl.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_join.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_join.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_main.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_meas.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_meas.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_misc.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_module.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_scan.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sdio.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sdio.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_shim.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_cmd.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_cmdresp.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_event.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_ioctl.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_rx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_tx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_txrx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_cmdevent.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_ioctl.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_txrx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_util.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_wmm.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_wmm.h 
rm -f drivers/staging/lustre/lustre/include/lustre_dlm_flags.h 
rm -f include/linux/i2c/mc3xxx.h 
rm -f include/linux/sensor/yas_android_lib.h 

